Updated Swagger for delivery (#120)
* DEL: payment response from swagger

* updated logout

* Update: CreateBookingRequest and POST create review endpoint

* Squashed commit of the following:

commit d3a97aed8a4808076473fff6df17dece2a5f30c7
Author: RBray9 <rjbray09@gmail.com>
Date:   Sun May 31 22:19:22 2026 +0100

    Update .proto files

* Squashed commit of the following:

commit 9dc2774c1b590d0e837e0fc080086b30abe0c833
Author: Reis <joaosimoesreis.jsr@gmail.com>
Date:   Sun May 31 22:39:23 2026 +0100

    updated tests

commit d3a97aed8a4808076473fff6df17dece2a5f30c7
Author: RBray9 <rjbray09@gmail.com>
Date:   Sun May 31 22:19:22 2026 +0100

    Update .proto files

* ADD: bearer auth to logout

* updated logout to not use token in the body

* fix: swagger compilation

* ADD: restaurant_id to create reservation

* removed token from logout body

* update test to new reservation request format

* fix: skip unchanged images on build

* fix: prebuild keycloak

---------

Co-authored-by: Reis <joaosimoesreis.jsr@gmail.com>
Co-authored-by: RBray9 <rjbray09@gmail.com>

diff --git a/.github/workflows/bruno.yml b/.github/workflows/bruno.yml
--- a/.github/workflows/bruno.yml
+++ b/.github/workflows/bruno.yml
@@ -62,6 +62,14 @@ jobs:
             cd - > /dev/null
           done
         
+      - name: Pull heavy images with retry
+        run: |
+          for image in quay.io/keycloak/keycloak:26.6.1; do
+            for i in 1 2 3; do
+              docker pull "$image" && break || (echo "Attempt $i failed, retrying..." && sleep 15)
+            done
+          done
+
       - name: Start services
         run: make build run
 
